### PR TITLE
fix: localisation in EmergencyRoomListViewCard

### LINKED ISSUE #50: position tracking on map
Localisation in EmergencyRoomListViewCard isn't implemented

### PR DESCRIPTION
**Pull request by Florian-Sabonchi**
in this Pull Request i added localistaion function on EmergencyRoomListViewCard and a floating-button for localisation on StreetMapViewPage

### CODE REVIEW

File: lib/styling/constants.dart [hunk 1]
```diff
@@ -45,8 +46,22 @@ const negativeColor = Color.fromARGB(255, 255, 51, 51);
...
 const Duration zeroDuration = Duration.zero;
-const Duration bottomSheetOpenDuration =  Duration(milliseconds: 100);
+const Duration bottomSheetOpenDuration = Duration(milliseconds: 100);
 
 // Font size
 const double fontSizeTiny = 12;
-const double fontSizeSmall = 14;
\ No newline at end of file
+const double fontSizeSmall = 14;
+
```
Comment (DasProffi) [inline lib/styling/constants.dart:54]: Please write a headding comment like `// OpenStreetMap`

**Review by DasProffi — CHANGES_REQUESTED** [review]

**Review by DasProffi — APPROVED** [review]
