### PR TITLE
fix: wrong organisation

### LINKED ISSUE #501: Wrong Patients loaded
### Describe the bug

Patients loaded which not linked to the selected organization

### Describe how to produce the bug

Create an organization and switch to this organization patients and tasks loaded which are not in this organization

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by florian-sabonchi**
## Which issues does this pull request close?
closes #501

### CODE REVIEW

**Comment by MaxSchaefer** [comment]
@florian-sabonchi why do you need to set the "correct" organisationId just for this one request? Why not set the current organizationId directly in `getTaskServiceMetaData`?

File: apps/tasks/lib/services/grpc_client_svc.dart [hunk 1]
```diff
@@ -40,6 +40,7 @@ class GRPCClientService {
       "dapr-app-id": "task-svc",
     };
 
+    metaData["X-Organization"] = fallbackOrganizationId!;
     if (organizationId != null) {
       metaData["X-Organization"] = organizationId;
     }
```
Comment (MaxSchaefer) [inline apps/tasks/lib/services/grpc_client_svc.dart:46]: Line #43 makes Line #44-46 obsolete and vice versa. Line #43 as a `else`-Condition would be good. The caller still has the ability to define an organizationId.

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]

File: apps/tasks/lib/services/grpc_client_svc.dart [hunk 2]
```diff
@@ -43,6 +43,9 @@ class GRPCClientService {
...
+    else {
```
Comment (MaxSchaefer) [inline apps/tasks/lib/services/grpc_client_svc.dart:46]:
```suggestion
    } else {
```

Comment (MaxSchaefer) [reply apps/tasks/lib/services/grpc_client_svc.dart:46]: Can you check our linter settings

**Review by MaxSchaefer — APPROVED** [review]
